CREATE TABLE IF NOT EXISTS KVStore
(
    id   TEXT PRIMARY KEY,
    data TEXT
) STRICT;
CREATE TABLE IF NOT EXISTS actions_list
(
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    data BLOB NOT NULL
) STRICT;